### ISSUE TITLE
Не работает

### ISSUE THREAD

**Issue by solara322** [ValeriyMaslenikov/tg-notify-deleted-messages#1]
Чем можно октрыть датабазу (messages.db), чтобы без кракозябр, так как в saved messages не отправляет удалённые.

**Comment by ValeriyMaslenikov** [comment]
Если все сделано в соответствии с инструкцией, то все должно работать, только что проверил на свежем инстансе. Чтобы протестировать, предлагаю изменить уровень логгирования в файле `.env` с `INFO` (значение по-умолчанию) на `DEBUG` и запустить приложение с привязкой к консоли (без флага `-d`: `docker-compose up app`). Самым простым способом проверить будет написать какому-то боту и удалить его сообщение (чтобы не подключать других людей), например [@JsonDumpBot](https://t.me/jsondumpbot). В логах должно отобразиться следующее сообщение: `INFO:root:Got 1 deleted messages. Has in DB 1. Users:...`. Возможно в момент написания удаленного сообщение, приложение просто не было запущено и не собрало это сообщение в свою БД. 

В БД `messages.db` не хранится текст сообщений в открытом виде, там хранятся сериализованные объекты класса [`Message`](https://lonamiwebs.github.io/Telethon/constructors/message.html), это значит что через какой-либо редактор открыть их не получится. 

Если нужно просто прочитать сохраненные сообщения предлагаю воспользоваться таким маленьким скриптом (заменив SQL-запрос и способ форматирование сообщения на нужный вам): 
```
import pickle
import sqlite3

from typing import List
from telethon.tl.types import Message

conn = sqlite3.connect("db/messages.db", check_same_thread=False)
c = conn.cursor()

db_result = c.execute("SELECT message_id, message FROM messages LIMIT 10").fetchall()

messages: List[Message] = [pickle.loads(i[1]) for i in db_result]

for message in messages:
    print(message.message + '\n')
```

Чтобы запустить его в контейнере, нужно добавить `volume` на этот скрипт, создав файл с именем `docker-compose.override.yml` и текстом (соответственно скрипт должен иметь имя deserialize.py): 
```
version: '3'

services:
  app:
    volumes:
      - ./deserialize.py:/usr/src/app/deserialize.py
```

Тогда запустить этот скрипт можно будет из консоли:
` docker-compose run app python deserialize.py`

**Comment by solara322** [comment]
@ValeriyMaslenikov 
Попытался поставить на виртуальный сервер, а там выводит ошибку. Что может быть не так?

``
root@user:/tg-notify-deleted-messages-master# python3 ./monitor.py auth        
  File "./monitor.py", line 100
    messages: List[Message] = [pickle.loads(i[1]) for i in db_result]
        ^
SyntaxError: invalid syntax
``

**Comment by ValeriyMaslenikov** [comment]
@solara322 прошу прощения за задержку с ответом. Если еще актуально, то я бы рекомендовал использовать докер (как установить: [docker](https://docs.docker.com/install/), [docker-compose](https://docs.docker.com/compose/install/) для разворачивания приложения. Вышеописанная вами ошибка, связана с тем что используется Python версии < 3.5.
